'use strict';
const C=Survival,$=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
let s=C.create(),mode='inside',player={x:520,y:390},keys=new Set(),target=null,route=null,travel=0,event=null,eventLeft=0,nextEvent=7+Math.random()*6,paused=false,deathTimer=null,last=0,uiTime=0,activeModal='',audioCtx=null,sound=false,lastBeep=0,journalPage=0;
const objects=[{id:'suit',name:'UV suit',x:845,y:210},{id:'filter',name:'Air filter',x:165,y:220},{id:'bench',name:'Workbench',x:330,y:235},{id:'cot',name:'Cot / wait',x:760,y:410},{id:'journal',name:'Journal',x:370,y:380},{id:'door',name:'Route map',x:975,y:290}];
function say(t){$('log').textContent=t}
function clock(h){let n=Math.floor(h*60)%1440;return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function outside(){return mode!=='inside'}
function effectiveUV(){return C.uvAt(s.hour)+(event==='flare'?4:0)}
function closeModal(){$('modal').close();activeModal='';keys.clear();last=performance.now()}
function openModal(type,html){keys.clear();target=null;activeModal=type;$('modalBody').innerHTML=html;if(!$('modal').open)$('modal').showModal()}
function nearest(){const list=mode==='inside'?objects:mode==='site'?[{id:'loot',name:'Search supplies',x:850,y:290},{id:'back',name:'Return route',x:130,y:420}]:[{id:'back',name:'Turn back',x:120,y:420}];return list.find(o=>Math.hypot(o.x-player.x,o.y-player.y)<95)}
function toggleSuit(){if(mode!=='inside')return;s.suited=!s.suited;say(s.suited?'Helmet sealed. Protection costs durability; heat and exposure can still build up.':'Suit back on its hook. UV 6+ is lethal without a working suit.');renderUI()}
function waitUntilDusk(){if(mode!=='inside')return;const minutes=((18-s.hour+24)%24)*60;if(minutes===0){say('It is already dusk.');return}C.tick(s,minutes,false,event);s.hour=18;event=null;eventLeft=0;say('You wait on the cot until 18:00. The filter and battery kept running.');checkDeath();renderUI()}
function interact(id){if(s.dead||paused)return;if(id==='suit')toggleSuit();else if(id==='door')planner();else if(id==='journal')journal();else if(id==='cot')waitUntilDusk();else if(id==='filter'||id==='bench')workbench();else if(id==='loot')loot();else if(id==='back')returnTrip()}
function planner(){if(mode!=='inside')return;let html='<div class="eyebrow">ROUTE PLANNING / DEPARTURE '+clock(s.hour)+'</div><h2>How far can you afford to go?</h2><p class="muted">One-way travel times. Suit estimates cover the full return trip, sample changing UV, and exclude scavenging time and random events. '+(s.suited?'Suit equipped.':'SUIT NOT EQUIPPED.')+' Current durability: '+Math.round(s.suit)+'%. Close this map to change departure time.</p><div class="routes">';for(const d of C.destinations){const f=C.forecast(s.hour,d.minutes,s.shield),blocked=!s.suited&&f.peak>=6;html+=`<article class="route"><h3>${d.name}</h3><p>${d.minutes} min one way · ${d.minutes*2} min round trip</p><p>Departure UV ${C.uvAt(s.hour).toFixed(1)} · peak on route ${f.peak.toFixed(1)}</p><p>Expected suit damage: ${Math.ceil(f.damage)}%</p><p>Possible loot: ${Object.keys(d.loot).map(i=>C.labels[i]).join(', ')}</p><p class="risk">${blocked?'LETHAL WITHOUT SUIT':f.damage>=s.suit?'SUIT MAY FAIL BEFORE RETURN':f.risk+' RISK'}${s.hour<6||s.hour>=20?' · Low visibility':''}</p><button data-route="${d.id}">Travel to ${d.name} ↗</button></article>`}openModal('plan',html+'</div>');$('modalBody').querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>depart(b.dataset.route))}
function depart(id){route=C.destinations.find(d=>d.id===id);if(!route)return;closeModal();mode='outbound';travel=0;player={x:140,y:420};target=null;event=null;eventLeft=0;nextEvent=3+Math.random()*7;say('You leave for '+route.name+'. Walk right along the road. Time, suit wear and exposure continue while you are outside.');C.tick(s,.01,true,null);checkDeath();renderUI()}
function returnTrip(){if(mode==='inside'||mode==='returning'||s.dead)return;closeModal();const distance=mode==='outbound'?Math.max(.5,Math.min(travel,route.minutes)):route.minutes;route={...route,returnMinutes:distance};mode='returning';travel=0;player={x:930,y:420};target={x:130,y:420};say('You turn toward home. Walk left to reach the shelter.');renderUI()}
function arrive(){if(mode==='outbound'){mode='site';player={x:180,y:420};target=null;s.visited.includes(route.id)||s.visited.push(route.id);say(route.name+'. Approach the supply cache and press E. The sun will not wait.')}else if(mode==='returning'){mode='inside';player={x:925,y:340};target=null;event=null;eventLeft=0;travel=0;say('Door sealed. You are home. Use supplies to repair the shelter, suit, or yourself.')}renderUI()}
function loot(){if(mode!=='site')return;let html='<div class="eyebrow">'+route.name.toUpperCase()+' / SEARCHING PAUSES TIME</div><h2>Take what you can carry.</h2><p>Pack: '+C.count(s)+' / '+s.capacity+' slots. Every unit takes one slot.</p>';for(const [item,n] of Object.entries(s.stock[route.id]))html+=`<div class="loot"><span>${C.labels[item]} × ${n}</span><button data-take="${item}" ${n===0||C.count(s)>=s.capacity?'disabled':''}>Take one</button></div>`;html+='<p class="note">'+route.note+'</p><p class="muted">Discard or use items from your pack after closing this menu. Finding the cache pauses time for reading; traveling and exploring do not.</p>';openModal('loot',html);$('modalBody').querySelectorAll('[data-take]').forEach(b=>b.onclick=()=>{if(C.take(s,route.id,b.dataset.take)){renderUI();loot()}})}
function workbench(){openModal('bench','<div class="eyebrow">SHELTER MAINTENANCE</div><h2>Make it last another day.</h2><p>Air filter: '+Math.round(s.filter)+'% · Power: '+Math.round(s.power)+'% · Suit: '+Math.round(s.suit)+'%</p><p>Use a filter cartridge to restore the air filter, a battery to restore 50 power, repair material for 45 suit durability, or shielding to reduce suit wear by 35%.</p><p class="muted">The filter and battery decay with game time, even while you wait on the cot. Empty air filtration or power damages your health indoors.</p><div id="benchItems"></div>');const box=$('benchItems');for(const item of ['filter','battery','scrap','shield']){const b=document.createElement('button');b.textContent='Use '+C.labels[item]+' ('+(s.bag[item]||0)+')';b.disabled=!s.bag[item];b.onclick=()=>{say(C.use(s,item,true));renderUI();workbench()};box.append(b)}}
function journal(){const pages=[`<h2>01 / Before we counted sunlight</h2><p>“I used to leave the house without checking the sky. Coffee. Class. A walk with no destination. Now every ordinary thing begins with waiting.”</p><p>This future self asks: which parts of my daily life could move into the dark, and which would I lose?</p><p class="muted">A speculative self-portrait using synthetic UV and invented routines. Replace these with 3–7 days of personal outings and local hourly UV observations.</p>`, `<h2>02 / The shape of a day</h2><svg class="uvplot" viewBox="0 0 600 140" role="img" aria-label="Synthetic UV peaks at 10 at 13:00 and reaches zero at night"><path d="${Array.from({length:97},(_,i)=>(i?'L':'M')+(20+i/96*560)+','+(110-C.uvAt(i/4)*8)).join(' ')}" fill="none" stroke="#d9a464" stroke-width="3"/><text x="20" y="135" fill="#b4b294" font-size="12">00:00</text><text x="280" y="135" fill="#b4b294" font-size="12">12:00</text><text x="545" y="135" fill="#b4b294" font-size="12">24:00</text></svg><p>Sample routine: 08:00 coffee (UV 1.9), 10:00 class (6.1), 13:00 walk (10), 18:00 dinner (1.9). Two of four outings start above the game’s unprotected lethal threshold.</p><p>Suit wear is 0.25 + 0.45 × UV per game minute. Night travel costs less durability, but hides more of the road. Route forecasts sample UV across both legs of the trip.</p>`, `<h2>03 / What remains</h2><p>Locations reached: ${s.visited.length}/5 · Filter replacements: ${s.repairs} · Events encountered: ${s.events}</p>${s.visited.map(id=>{const d=C.destinations.find(d=>d.id===id);return '<p class="note"><b>'+d.name+'</b><br>'+d.note+'</p>'}).join('')||'<p>The journal is empty. Search a destination for traces of the people who lived here.</p>'}<p class="muted">All survival thresholds, events, suit behavior, and UV values are fictional. They are not real protective-equipment or exposure guidance.</p>`];openModal('journal','<div class="eyebrow">RECOVERED JOURNAL / '+(journalPage+1)+' OF 3</div>'+pages[journalPage]+'<div class="journal-nav"><button id="previousPage" '+(journalPage===0?'disabled':'')+'>← Previous</button><button id="nextPage" '+(journalPage===2?'disabled':'')+'>Next →</button></div>');$('previousPage').onclick=()=>{journalPage--;journal()};$('nextPage').onclick=()=>{journalPage++;journal()}}
function randomEvent(){const options=['flare','dust','power','seal','blocked'];event=options[Math.floor(Math.random()*options.length)];eventLeft=3+Math.random()*3;s.events++;if(event==='power')s.power=Math.max(0,s.power-25);if(event==='seal')s.suit=Math.max(0,s.suit-8);say({flare:'SOLAR FLARE. Surface UV jumps by 4. Protection is burning faster.',dust:'DUST STORM. Visibility drops; the shelter filter clogs faster. Dust hurts outside.',power:'POWER OUTAGE. The shelter backup lost 25 power. Bring a battery home.',seal:'DAMAGED SEAL. Suit lost 8 durability and will wear twice as fast temporarily.',blocked:'BLOCKED ROUTE. A collapsed wall forces a detour; travel progress is halved.'}[event])}
function checkDeath(){if(!s.dead)return;if(deathTimer)return;keys.clear();target=null;closeModal();$('death').hidden=false;$('deathReason').textContent=s.reason;deathTimer=setTimeout(()=>{s=C.create();mode='inside';player={x:520,y:390};route=null;event=null;eventLeft=0;travel=0;paused=false;deathTimer=null;$('death').hidden=true;nextEvent=7+Math.random()*6;say('You wake to the same air filter. All supplies, suit wear, and routes have reset. Try another departure time.');renderUI()},3500)}
function renderUI(){for(const key of ['suit','exposure','heat','filter']){$(key+'Meter').value=s[key];$(key+'Label').textContent=Math.round(s[key])+'%'+(key==='suit'?(s.suited?' / ON':' / OFF'):'')} $('clock').textContent=clock(s.hour);$('uv').textContent='UV '+effectiveUV().toFixed(1);$('health').textContent='HEALTH '+Math.round(s.health)+'%';$('power').textContent='POWER '+Math.round(s.power)+'%';$('capacity').textContent=C.count(s)+' / 6';$('suit').textContent=s.suited?'Take off UV suit':'Put on UV suit';$('suit').disabled=outside()||s.dead;$('suit').setAttribute('aria-pressed',String(s.suited));$('plan').hidden=outside();$('return').hidden=!outside();$('return').disabled=mode==='returning'||s.dead;$('time').disabled=outside()||s.dead;$('time').value=s.hour;$('timeHint').textContent=outside()?'Time runs while you are outside':'Inside only · reposition the sun';$('place').textContent=mode==='inside'?'YOUR SHELTER':mode==='site'?route.name.toUpperCase():mode==='returning'?'RETURNING TO SHELTER':'ROAD TO '+route.name.toUpperCase();$('weather').textContent=event?event.toUpperCase():s.hour<6||s.hour>=20?'NIGHT / LOW VISIBILITY':effectiveUV()>=6?'HOSTILE DAYLIGHT':'THE LIGHT SOFTENS';$('objective').textContent=s.repairs?'Air restored. Keep the shelter supplied and recover stories from all five destinations.':'Recover a filter cartridge from the research station and restore the shelter’s air.';$('pause').textContent=paused?'Resume':'Pause';
 const bagHTML=Object.entries(s.bag).filter(([,n])=>n>0).map(([i,n])=>`<div class="item"><span>${C.labels[i]} ×${n}</span><span class="item-actions"><button data-use="${i}">Use</button><button data-drop="${i}" aria-label="Discard one ${C.labels[i]}">Drop</button></span></div>`).join('')||'<p class="muted">Your pack is empty.</p>';if($('inventory').innerHTML!==bagHTML){$('inventory').innerHTML=bagHTML;$('inventory').querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{if(s.dead)return;say(C.use(s,b.dataset.use,!outside()));renderUI()});$('inventory').querySelectorAll('[data-drop]').forEach(b=>b.onclick=()=>{if(s.dead)return;C.consume(s,b.dataset.drop);say('Left behind one '+C.labels[b.dataset.drop]+'.');renderUI()})}
 const list=mode==='inside'?objects:mode==='site'?[{id:'loot',name:'Search cache'},{id:'back',name:'Head home'}]:[{id:'back',name:'Turn back'}];const html=list.map(o=>`<button data-object="${o.id}">${o.name}</button>`).join('');if($('objects').innerHTML!==html){$('objects').innerHTML=html;$('objects').querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>{if(mode==='inside'){const o=objects.find(o=>o.id===b.dataset.object);player={x:o.x,y:Math.min(440,o.y+60)}}else if(b.dataset.object==='loot')player={x:810,y:340};interact(b.dataset.object)})}}
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h)}function text(t,x,y,color='#c8b58b',size=12){ctx.fillStyle=color;ctx.font=size+'px monospace';ctx.fillText(t,x,y)}function line(x,y,x2,y2,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke()}function ellipse(x,y,rx,ry,c){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function drawCharacter(x,y,t){const walk=keys.size||target?Math.sin(t/100)*4:0;ctx.save();ctx.translate(x,y);if(s.dead){ctx.globalAlpha=.25;for(let i=0;i<18;i++)rect(Math.sin(i*7)*28,-i*5,3,3,'#f1c778');ctx.restore();return}ellipse(0,10,19,7,'#0c110ba0');line(-7,-5,-8,9+walk,'#283024',8);line(7,-5,8,9-walk,'#283024',8);rect(-14,-33,28,29,s.suited?'#a8ae91':'#94714c');line(-16,-28,-19,-9-walk,s.suited?'#a8ae91':'#94714c',7);line(16,-28,19,-9+walk,s.suited?'#a8ae91':'#94714c',7);ellipse(0,-44,15,17,s.suited?'#b9bba0':'#c09f70');rect(-11,-49,22,10,s.suited?'#30473c':'#453d2b');line(-7,-45,5,-45,'#deb875',2);if(s.suited){rect(-5,-36,10,7,'#58694e');rect(-5,-21,10,9,s.suit<20?'#d46c47':'#ccbe79')}ctx.restore()}
function draw(t){const u=effectiveUV(),night=s.hour<6||s.hour>=20;ctx.clearRect(0,0,1100,600);if(mode==='inside'){
 rect(0,0,1100,600,'#252b20');rect(65,95,970,365,'#414634');rect(65,310,970,150,'#393f2f');rect(0,460,1100,140,'#262e20');for(let x=0;x<1100;x+=100)line(550+(x-550)*.8,460,x,600,'#343d2a');line(65,95,1035,95,'#6b6a4c');rect(460,112,300,167,night?'#18272a':u>6?'#d1ac68':'#917a58');for(let i=0;i<9;i++)rect(470+i*33,215-(i%3)*20,23,64+(i%3)*20,night?'#1a2220':'#6e6445');if(!night){const f=(s.hour-6)/14;ellipse(480+260*f,220-Math.sin(f*Math.PI)*72,23,23,'#efc57d')}rect(454,106,312,9,'#151e15');rect(454,277,312,9,'#151e15');rect(454,112,9,165,'#151e15');rect(757,112,9,165,'#151e15');rect(606,112,9,165,'#273421');if(!night){ctx.fillStyle=`rgba(243,195,105,${.03+u*.014})`;ctx.beginPath();ctx.moveTo(470,285);ctx.lineTo(750,285);ctx.lineTo(970,535);ctx.lineTo(560,535);ctx.fill()}
 rect(108,160,110,128,'#262f22');for(let i=0;i<7;i++)rect(120,171+i*10,86,4,'#656e4c');ellipse(129,262,5,5,s.filter>30?'#a9b57c':'#d58952');text('AIR',146,266);line(140,155,140,112,'#666d4e',14);
 rect(255,270,170,17,'#8c7b53');rect(267,287,12,51,'#4a5037');rect(400,287,12,51,'#4a5037');rect(286,191,93,76,'#1d2a1d');text('UV '+u.toFixed(1),296,218,'#cead68',16);for(let i=0;i<40;i++){const v=C.uvAt(i/39*24);rect(296+i*1.7,252-v*2,2,2,'#a6b57d')}text('WORKBENCH',270,177,'#b8ab7f',11);
 rect(710,403,140,44,'#686e4d');rect(710,391,140,29,'#8d8a66');rect(719,388,34,24,'#c2b18a');line(718,448,718,469,'#50573e',6);line(843,448,843,469,'#50573e',6);
 rect(925,156,99,189,'#1c291c');rect(934,166,80,177,'#515a3d');line(940,174,1006,330,'#747251',7);line(1006,174,940,330,'#747251',7);ellipse(996,265,10,10,'#242e1e');text('SURFACE',939,146,'#c2ab76',11);
 rect(345,367,45,25,'#ad9768');line(367,367,367,392,'#69583a');text('JOURNAL',339,355,'#b4a980',10);
 line(843,127,843,152,'#a0a07c',3);if(!s.suited){drawCharacter(845,216,0);text('UV SUIT',817,245,'#c2bb8d',11)}else{text('EMPTY HOOK',807,177,'#8b9372',10)}text('STAY BELOW',468,83,'#9f9e76',17);
 }else{const sky=ctx.createLinearGradient(0,0,0,350);sky.addColorStop(0,night?'#121d22':u>=6?'#aaa07a':'#6e6e58');sky.addColorStop(1,night?'#30372c':u>=6?'#ddbc79':'#b39165');ctx.fillStyle=sky;ctx.fillRect(0,0,1100,600);if(!night){ellipse(550,100,100,100,'#efd19718');ellipse(550,100,42,42,u>=6?'#ffe1a1':'#dfb376')}else{for(let i=0;i<35;i++)rect((i*173)%1100,(i*67)%190,2,2,'#a8b5a155')}
 for(let i=0;i<16;i++){const x=i*78,h=70+(i*43)%120;rect(x,310-h,55,h,night?'#222b22':'#655d41');for(let j=0;j<3;j++)rect(x+10+j*14,323-h,5,14,'#aaa16a22')}rect(0,310,1100,290,night?'#283023':'#796646');rect(0,365,1100,130,night?'#343c2a':'#9b8153');for(let i=0;i<20;i++)line(i*63,500+(i%4)*20,i*63+28,510+(i%4)*20,'#46482f');
 if(mode==='site'){rect(760,217,190,151,'#4e573c');rect(744,205,223,20,'#77764f');rect(815,280,75,88,'#1b281d');text(route.name.toUpperCase(),760,191,'#d1c296',15);rect(816,307,67,48,'#87835a');line(825,307,825,355,'#353e28',4);line(874,307,874,355,'#353e28',4);text('SUPPLIES',817,334,'#242e1d',10);text('← HOME',90,377,'#d4c692',14)}else{const need=mode==='returning'?route.returnMinutes:route.minutes;const percent=Math.min(100,travel/need*100);text((mode==='returning'?'← SHELTER':'DESTINATION →')+'   '+Math.floor(percent)+'%',440,330,'#e0d2a6',14);rect(400,345,300,5,'#434b30');rect(400,345,300*percent/100,5,'#c2b278');text(mode==='returning'?'Walk left to the shelter':'Walk right to the destination',400,555,'#d5c594',13)}
 if(night){const light=ctx.createRadialGradient(player.x,player.y-20,30,player.x,player.y-20,230);light.addColorStop(0,'#0000');light.addColorStop(1,'#050c09cf');ctx.fillStyle=light;ctx.fillRect(0,0,1100,600)}if(event==='dust'){ctx.fillStyle='#b5a36b44';ctx.fillRect(0,0,1100,600);for(let i=0;i<60;i++)line((i*73+t*.12)%1100,(i*41)%600,(i*73+t*.12)%1100+25,(i*41)%600-3,'#d0be8055')}
 }
 const n=nearest();if(n){ellipse(n.x,n.y+5,31,10,'#cfbb6633');text('[E] '+n.name,n.x-43,n.y-65,'#e0d9ad',11)}drawCharacter(player.x,player.y,t);if(outside()&&u>=6){rect(0,0,1100,3,Math.sin(t/250)>0?'#db9059':'#513c24')}if(paused){rect(0,0,1100,600,'#10170d99');text('PAUSED',495,280,'#e3cea0',28)}$('prompt').textContent=paused?'PAUSED · Resume below':s.dead?'SIGNAL LOST':n?'E · '+n.name:'W A S D / ARROWS to move · Click ground to walk';
}
function beep(now){if(!sound||!audioCtx||now-lastBeep<1800||!outside()||effectiveUV()<6)return;lastBeep=now;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=s.suit<25?740:400;g.gain.setValueAtTime(.025,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.12);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.13)}
function frame(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;if(!paused&&!$('modal').open&&!s.dead&&!document.hidden){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dy)target=null;else if(target){dx=target.x-player.x;dy=target.y-player.y;if(Math.hypot(dx,dy)<5){target=null;dx=dy=0}}const length=Math.hypot(dx,dy);if(length){const speed=event==='blocked'?95:155;player.x=Math.max(85,Math.min(1010,player.x+dx/length*speed*dt));player.y=Math.max(mode==='inside'?185:355,Math.min(545,player.y+dy/length*speed*dt))}const mins=dt*(outside()?.5:.08);C.tick(s,mins,outside(),event);if(outside()){nextEvent-=mins;if(nextEvent<=0&&!event){randomEvent();nextEvent=8+Math.random()*10}if(event){eventLeft-=mins;if(eventLeft<=0){event=null;say('The disturbance passes. Check your suit and supplies.')}}if(mode==='outbound'||mode==='returning'){travel+=mins*(event==='blocked'?.5:1);const need=mode==='returning'?route.returnMinutes:route.minutes;if(travel>=need&&(mode==='returning'?player.x<180:player.x>920))arrive()}beep(now)}checkDeath();uiTime+=dt;if(uiTime>.3){renderUI();uiTime=0}}draw(now);requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{if($('modal').open||['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e'].includes(key)){e.preventDefault();if(key==='e'){if(!e.repeat){const o=nearest();if(o)interact(o.id)}}else keys.add(key)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();target=null});document.addEventListener('visibilitychange',()=>{keys.clear();target=null;last=performance.now()});canvas.addEventListener('pointerdown',e=>{if(paused||s.dead||$('modal').open)return;document.activeElement.blur();const r=canvas.getBoundingClientRect();target={x:(e.clientX-r.left)/r.width*1100,y:(e.clientY-r.top)/r.height*600};const o=mode==='inside'?objects.find(o=>Math.hypot(o.x-target.x,o.y-target.y)<45):null;if(o){player={x:o.x,y:o.y+60};target=null;interact(o.id)}});
$('suit').onclick=toggleSuit;$('plan').onclick=planner;$('return').onclick=returnTrip;$('journal').onclick=journal;$('pause').onclick=()=>{paused=!paused;keys.clear();renderUI()};$('close').onclick=closeModal;$('modal').addEventListener('cancel',()=>{activeModal='';keys.clear()});$('time').addEventListener('input',()=>{if(outside())return;s.hour=Number($('time').value);event=null;say('Departure set to '+clock(s.hour)+'. Open the route map to compare round-trip suit costs.');renderUI()});$('sound').onclick=()=>{sound=!sound;if(sound){const AC=window.AudioContext||window.webkitAudioContext;if(AC){audioCtx=audioCtx||new AC();audioCtx.resume()}else sound=false}$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound))};renderUI();requestAnimationFrame(frame);
